apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sentinel-controller.fullname" . }}
  labels:
    {{- include "sentinel-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sentinel-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sentinel-controller.serviceAccountName" . }}
    namespace: {{ .Values.controllerNamespace | quote }}
